baseURL = "https://felixogon.github.io/"
languageCode = "en-us"
title = "Felix Ogon"
theme = "PaperMod"
defaultTheme = "dark"

[params]
    env = "production"
    title = "Felix Ogon"
    description = "Caltech MS EE | ETH Zurich BS ME"
    
    # PaperMod specific CSS loading
    [params.assets]
        customCSS = ["css/custom.css"]

    [params.profileMode]
        enabled = true
        title = "Felix Ogon"
        subtitle = "incoming MS EE Student at Caltech | Robotics & AI"
        [[params.profileMode.buttons]]
            name = "Experience"
            url = "experience"
        [[params.profileMode.buttons]]
            name = "Projects"
            url = "projects"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/felixogon"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/felix-ogon-599823292/"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:felixmichael.ogon@gmail.com"

[menu]
    [[menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/experience"
        weight = 10
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 20
